cli_homepage:
    path:     /
    defaults: { _controller: CliBundle:Default:index }

api_update:
    path: /api/update/{slug}
    defaults: { _controller: CliBundle:UpdateController:index }
    methods: [POST]